name: Publish to Chrome Web Store
on:
  create:
    tags:
      - v*

jobs:
  build:
    name: Publish
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: zip dist
        uses: montudor/action-zip@v0.1.0
        with:
          args: zip -qq -r ./extension.zip ./extension
      - name: upload
        uses: trmcnvn/chrome-addon@v2
        with:
          extension: adfoofaganimefeanophhfkmdiaaoglo
          zip: extension.zip
          client-id: ${{ secrets.CHROME_CLIENT_ID }}
          client-secret: ${{ secrets.CHROME_CLIENT_SECRET }}
          refresh-token: ${{ secrets.CHROME_REFRESH_TOKEN }}